import enum


class Errors(enum.IntEnum):
    IS_NOT_ROOT = 101
    WRONG_PHASE = 102
    LOW_OPEN_DURATION = 103
    LOW_MSG_VALUE = 104
    LOW_STEP_VALUE = 201
    VALUE_LESS_THAN_START_VALUE = 203
    VALUE_LESS_THAN_STEP_FROM_HIGHEST_VALUE = 204
    VALUE_MORE_THAN_START_VALUE = 205
    VALUE_MORE_THAN_STEP_FROM_LOWEST_VALUE = 206
    START_LESS_THAN_FINISH = 301
    START_MORE_THAN_FINISH = 302
    VALUE_LESS_THAN_CURRENT_PRICE = 303
    VALUE_MORE_THAN_CURRENT_PRICE = 304
    LOW_FEE_VALUE = 401
    LOW_DEPOSIT_VALUE = 402
    VALUE_LESS_THAN_DEPOSIT = 403
    IS_NOT_FROM_BID = 404
    NOT_ENOUGH_TOKENS = 405
    IS_NOT_AUCTION = 444
    IS_NOT_INITED = 501
    IS_ALREADY_INITED = 502
    LOW_DEPLOY_VALUE = 503
    AUCTIONS_CODES_NOT_INITED = 504
